apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-otrder-app-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: environments/dev/apps
    repoURL: https://github.com/ramanujds/idcube-ops-repo.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true