apiVersion: apps/v1
kind: Deployment
metadata:
  name: part-inventory-service
#  namespace: dev
  labels:
    app: part-inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: part-inventory-service
  template:
    metadata:
      labels:
        app: part-inventory-service
    spec:
      containers:
        - name: part-inventory-service
          image: ram1uj/part-inventory-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "part_inventory_db"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: "400m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "512Mi"
