apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: order=ram1uj/part-order-service
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:environments/dev/values/order-values.yaml
    argocd-image-updater.argoproj.io/order.helm.image-name: partOrder.image.repository
    argocd-image-updater.argoproj.io/order.helm.image-tag: partOrder.image.tag
    argocd-image-updater.argoproj.io/order.update-strategy: newest-build
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  sources:
    - path: order-app-chart
      repoURL: https://github.com/ramanujds/gitops-repo-forvia
      targetRevision: HEAD
      helm:
        releaseName: order-service
        valueFiles:
          - $values/environments/dev/values/order-values.yaml
    - repoURL: https://github.com/ramanujds/gitops-repo-forvia
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true