apiVersion: v1
kind: Service
metadata:
  name: part-order-service
#  namespace: dev
  labels:
    app: part-order-service
spec:
  selector:
    app: part-order-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
